### ISSUE TITLE
WaylandXdgOutputV1: No such file or directory

### ISSUE THREAD

**Issue by skaendo** [lirios/aurora-compositor#35] opened 2023-02-09 00:19 UTC
Trying to build aurora-compositor and I am getting a hard fail.
Not sure why, maybe I'm missing something. 
Build environment: Slackware64-15.0 & current.

Here is the fail, I also posted a full build log on pastebin here: https://pastebin.com/JRCZ4wFM

> [ 21%] Automatic MOC and UIC for target AuroraCompositor
> AutoMoc: /tmp/endo/aurora-compositor-1ade4f3b3e75e18ee2d804985bbaee356cbd4e96/src/compositor/global/aurorawaylandquickextension.h:0: Note: No relevant classes found. No output generated.
> [ 21%] Built target AuroraCompositor_autogen
> [ 21%] Generating qrc_compositor.cpp
> [ 22%] Building CXX object src/compositor/CMakeFiles/AuroraCompositor.dir/AuroraCompositor_autogen/mocs_compilation.cpp.o
> In file included from /tmp/endo/aurora-compositor-1ade4f3b3e75e18ee2d804985bbaee356cbd4e96/build/src/compositor/AuroraCompositor_autogen/5JE3FL2PJN/moc_aurorawaylandquickxdgoutputv1.cpp:10,
>                  from /tmp/endo/aurora-compositor-1ade4f3b3e75e18ee2d804985bbaee356cbd4e96/build/src/compositor/AuroraCompositor_autogen/mocs_compilation.cpp:28:
> /tmp/endo/aurora-compositor-1ade4f3b3e75e18ee2d804985bbaee356cbd4e96/build/src/compositor/AuroraCompositor_autogen/5JE3FL2PJN/../../../../../src/compositor/extensions/aurorawaylandquickxdgoutputv1.h:9:10: fatal error: LiriAuroraCompositor/WaylandXdgOutputV1: No such file or directory
>     9 | #include <LiriAuroraCompositor/WaylandXdgOutputV1>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/compositor/CMakeFiles/AuroraCompositor.dir/build.make:568: src/compositor/CMakeFiles/AuroraCompositor.dir/AuroraCompositor_autogen/mocs_compilation.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:630: src/compositor/CMakeFiles/AuroraCompositor.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2

**Comment by n3rdopolis** [comment] 2023-02-09 14:17
I can confirm I get this too. I was just about to report this, seems to be a newish commit, but I can't isolate it to which one yet

**Comment by plfiorini** [comment] 2023-04-18 21:21
Fixed with https://github.com/lirios/cmake-shared/commit/b1e33eb4145d997ae6b3e823d846a9e52be14610

**Closed as completed** 2023-04-18 21:21 UTC
